# Generated by Django 4.1.2 on 2022-10-19 12:58

import app.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_options_alter_brand_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[app.utils.validate_past_order_date]),
        ),
    ]
